packages:
  - packages/*
  - examples/*
linkWorkspacePackages: true
preferWorkspacePackages: true
allowBuilds:
  '@google/genai': false
  '@mongodb-js/zstd': false
  cpu-features: false
  esbuild: false
  node-liblzma: false
  protobufjs: false
  ssh2: false
